Python 2.7:
  script:
  - py_version=2.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.5:
  script:
  - py_version=3.5
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.7:
  script:
  - py_version=3.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml
